{% set version = "6.0" %}
{% set sha256 = "036d96991646d0449ed0aa952e4fbe21b476ce994abc276e49d30e686708bd37" %}

package:
  name: unzip
  version: {{ version }}

source:
  url: ftp://ftp.info-zip.org/pub/infozip/src/unzip{{ version.replace(".", "") }}.tgz
  sha256: {{ sha256 }}
  patches:
   - avoid_cr.patch  # [win]

build:
  number: 3
  script:
   # Can't build with bzip2 support due to:
   # > A bzip2 library built with BZ_NO_STDIO should have an
   # > unresolved external, "bz_internal_error".  The default,
   # > full-function library will not mention it.
   - make -f unix/Makefile CC=$CC prefix="$PREFIX" CF="$CFLAGS -I." LFLAGS1="$LDFLAGS" generic  # [osx]
   - make -f unix/Makefile CC=$CC prefix="$PREFIX" CF="$CFLAGS -I. -DNO_LCHMOD" LFLAGS1="$LDFLAGS" unzips  # [linux]
   - make prefix="$PREFIX" -f unix/Makefile install  # [unix]
   - make -f win32/Makefile.gcc CC=$CC prefix="$PREFIX" CF="$CFLAGS -I." LFLAGS1="$LDFLAGS" NOASM=1 USE_POSIX=1  # [win]
   - xcopy /y /s *.exe *.dll %LIBRARY_BIN%  # [win]

requirements:
  build:
    - {{ compiler('c') }}  # [unix]
    - {{ compiler('m2w64_c') }}  # [win]
    - make

test:
  commands:
    - unzip -h
    - zipinfo -h
    # Ensure lchmod is not being used by the binary
    - test "$(strings $(which unzip) | grep -ci lchmod)" -eq 0  # [linux]

about:
  home: http://www.info-zip.org/
  license: LicenseRef-BSD-like
  license_file: LICENSE
  summary: simple program for unzipping files

extra:
  recipe-maintainers:
    - chrisburr
    - msarahan
    - jerowe
